//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bundler.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BundlerLog
    {
        public System.DateTime Timestamp { get; set; }
        public string Satus { get; set; }
        public Nullable<int> IncomeFrom { get; set; }
        public Nullable<int> IncomeTo { get; set; }
        public Nullable<int> AgeFrom { get; set; }
        public Nullable<int> AgeTo { get; set; }
    }
}
